version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeFLOW_TEST_23_08
  gitServerName: testGitP1
  gitUrl: https://github.com/PoojaAnandGit/EdgeFLOW_TEST_23_08
  gitUsername: PoojaAnandGit
  gitToken: edge.scaffolding.EdgeFLOW_TEST_23_08.testGitP1.gitToken
  gitBranch: main
